### ISSUE TITLE
大佬，我repsonse的json数据都被phantomjs给url编码了怎么办啊，求解答，谢谢

### ISSUE THREAD

**Issue by luciffer-yu** [c0ny1/jsEncrypter#10]
插件很好用，但是碰到一个蛋疼问题，我从js里面console.log打出来的json数据都还是对的，但是response写回去的时候，就 { } “ ”全部被url编码了，然后发给服务器就错误了，有没有什么办法避免啊，查了半天phantomjs接口文档，好像只有对request可以设置ajax那样的发json数据，对于response没有设置可以用，求大佬解答，谢谢
![333](https://user-images.githubusercontent.com/16314456/75462009-864be300-59be-11ea-88af-42acc31e66b0.png)

![222](https://user-images.githubusercontent.com/16314456/75462290-ffe3d100-59be-11ea-8566-498837407558.png)

![111](https://user-images.githubusercontent.com/16314456/75461622-045bba00-59be-11ea-8d82-740e55162752.png)

**Comment by c0ny1** [comment]
你这个应该不是插件的问题，而是burp intruder设置的问题。应该将下面的设置去掉打勾。
![image](https://user-images.githubusercontent.com/15975792/75498084-2b87ab00-5a01-11ea-92e0-877577af6709.png)

**Comment by luciffer-yu** [comment]
> 你这个应该不是插件的问题，而是burp intruder设置的问题。应该将下面的设置去掉打勾。
> ![image](https://user-images.githubusercontent.com/15975792/75498084-2b87ab00-5a01-11ea-92e0-877577af6709.png)

多谢大佬这么快回复，我试了下URL-encode 我没有勾选的，不过给了我启发，我在Payload Processing 加了一个URL-decode方法就解决了，谢谢！！！
![444](https://user-images.githubusercontent.com/16314456/75501432-fd0ecd80-5a0a-11ea-978a-7bd4a3e70f7c.png)
