### ISSUE TITLE
关于换行和同时加密不同算法的参数

### ISSUE THREAD

**Issue by iceofrace** [c0ny1/jsEncrypter#11]
大佬请教下使用nodejs_server.js的2个问题：
1.换行
0.3.2版本中，在终端换行正常，在burp插件中没有换行，爆破的时候也没有换行，是我的burp版本不对么？
![image](https://user-images.githubusercontent.com/63698224/79301905-5a100580-7f1d-11ea-9469-c2c2a63b5fe1.png)
2.同时加密不同算法的参数
可以同时输入几个不同参数并调用不同的密码算法么？因为会遇到防重放，防篡改的问题，或者能否启动多个服务，目前是拼接方式实现的

**Comment by iceofrace** [comment]
嗯~ o(*￣▽￣*)o，我看到已关闭的问题，可以临时解决问题，先谢了。

**Comment by c0ny1** [comment]
1. nodejs_server.js已经不推荐使用了，后续没有怎么更新它。推荐使用pantomjs_server.js。
2. 是可以的。采用的就是启动多个加密服务和加载多个jsEncrypter插件来解决。

**Comment by iceofrace** [comment]
好的，我试试，3Q
