### ISSUE TITLE
Burp汉化界面密码没有换行，英文界面正常

### ISSUE THREAD

**Issue by Mr-xn** [c0ny1/jsEncrypter#5]
一个不算 ~Bug~ 的 *Bug* ，在英文界面下没问题，但是在汉化界面下会出现密码没有换行这种情况：![密码没有换行](https://i.imgur.com/IqmNHZc.png)
另外我在[这里](https://github.com/Mr-xn/Burp-Suite-collections)引用了你的两个 Repo 哈哈

**Comment by c0ny1** [comment]
Burp汉化版下，payload没有换行显示问题已解决，请自行编译最新代码。

![jsEncrypter](https://user-images.githubusercontent.com/15975792/56055305-c5b01780-5d8b-11e9-831b-6a78e4da8c1d.png)

注意：在Burp汉化版下，依然存在一个小坑。插件的文本域控件（JTextArea）在Windwos下（其他系统未测试）键盘输入时，依然无法换行。经过测试其他插件也是如此。但这个并不影响该插件的使用。故该遗留小问题后期再解决！

**Comment by Mr-xn** [comment]
> Burp汉化版下，payload没有换行显示问题已解决，请自行编译最新代码。
> 
> ![jsEncrypter](https://user-images.githubusercontent.com/15975792/56055305-c5b01780-5d8b-11e9-831b-6a78e4da8c1d.png)
> 
> 注意：在Burp汉化版下，依然存在一个小坑。插件的文本域控件（JTextArea）在Windwos下（其他系统未测试）键盘输入时，依然无法换行。经过测试其他插件也是如此。但这个并不影响该插件的使用，故该遗留小问题后期再解决！

OK
