### ISSUE TITLE
插件太强了 师傅太强了

### ISSUE THREAD

**Issue by TheKingOfDuck** [c0ny1/jsEncrypter#6]
实名膜拜师傅~ 17年的插件了最近才找到 相见恨晚？
贼强 贼强 贼强
早些时间遇到魔改的base64 或者sha1这类burp无法完成快捷加密的算法时都只得自己写py来还原加密算法或者利用python的execjs模块实现  有了师傅的这插件就再不需要了 实名膜拜

![duck](https://user-images.githubusercontent.com/27769271/59147750-fa5de980-8a31-11e9-9c3c-c3d377530c95.jpg)

**Comment by c0ny1** [comment]
过奖了，希望插件能节省师傅一些时间^_^
