### ISSUE TITLE
burp插件提示connect失败

### ISSUE THREAD

**Issue by 779789571** [c0ny1/jsEncrypter#7]

**Comment by 779789571** [comment]
phantomJS已经正常执行待命中,burp插件里点击connect后提示false,host和port输入也都是正确的,按理说应该提示true呀,会不会是跟网站是采用https的有关系呢?

**Comment by ws4** [comment]
估计是你使用的是旧的phantom_server.js,旧的脚本运行不报错退出，会出现僵死状态。

**Comment by 779789571** [comment]
那我应该怎么做去解决这个问题呢?下载一个新的phantom吗?

**Comment by c0ny1** [comment]
@779789571 https://github.com/c0ny1/jsEncrypter/blob/master/script/phantomjs_server.js，看下你使用的模版是这个么

**Comment by 779789571** [comment]
是的,启动后cmd里面提示加载js成功后就没有任何报错信息啦. burp插件的output信息里有反馈是connect fail!

**Comment by c0ny1** [comment]
1. 注意排查下插件连接的端口
2. 访问下本地的http://127.0.0.1:1664,是否显示加密端运行成功

如果两个都正常，还是不行的话。方便的话，可以发下你的调用代码或目标站点

**Comment by 779789571** [comment]
今天再试了一下,phantomjs启动大佬编写的脚本比如jsEncrypter_sha1.js,连接本地127.0.0.1:1664,burp点击connect可正常返回加密的密文,但仅仅把js脚本里的ip及端口修改为内网地址及端口后再次启动phantomjs,burp插件就提示connect失败了,初步判定不是我js编写的问题,目标地址是在内网下的https站点.提供不了

**Comment by c0ny1** [comment]
你的使用方法错误，脚本的地址并不是目标网站的IP和端口。你只需要从目标网站获取加密函数并在脚本中调用，其他无需修改。具体可以看看readme
