### ISSUE TITLE
不同加密方法的多参数爆破

### ISSUE THREAD

**Issue by BonjourM3** [c0ny1/jsEncrypter#8]
师傅，这个插件能对使用同一JS文件加密但加密方法不同的多个参数进行爆破吗。XD
例如：
var account =$.base64.encode( $('#username').val());
var password= $.hex_md5($('#password').val());
实现对两个参数进行同时爆破

**Comment by c0ny1** [comment]
目前还不支持。但有一个方法，你把插件复制两份，加载到burp中。然后分别配置好base64加密和md5加密就可以同时爆破了。

**Comment by BonjourM3** [comment]
> 目前还不支持。但有一个方法，你把插件复制两份，加载到burp中。然后分别配置好base64加密和md5加密就可以同时爆破了。

好的，谢谢师傅
