### ISSUE TITLE
求个需求实现

### ISSUE THREAD

**Issue by Curta7n** [c0ny1/jsEncrypter#9]
今天遇到了一个前端加密的登陆点,用师傅的方法很快找到了加密函数,不过他是post数据包中所有的数据统一加密发送,不仅仅加密某个参数的值.
然后就有了个新的需求,就是能不能在插件内部导入字典,然后指定替换点.类似变量之类的.其他部分内容不变,生成加密后数据.
或者师傅有没有什么其他的突破思路?

**Comment by c0ny1** [comment]
是每个参数的值被加密了，然后整体的请求的数据也被加密了，是这个意思么

**Comment by Curta7n** [comment]
参数没有被加密,但是整个请求被加密了.

**Comment by c0ny1** [comment]
这个问题，比较难在插件里解决，这是因为受限于burp Intruder模块的机制。当然有一个折中的解决方案是
1. Intruder选中整个请求体，并配置插件来加密
2. 编写一个python脚本，加载字典生成对应的请求体字典，最后加载到intruder

**Comment by Curta7n** [comment]
ok.之前想的也就是这样了 :)
